#!/bin/bash

# ZSH CONFIGURATION
# =============================================================================
# For more, see: ZSH CUSTOM CONFIGURATION

# Path to your oh-my-zsh installation.
export ZSH=/Users/medinaj/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

# my oh zsh
source $ZSH/oh-my-zsh.sh

# PATH CONFIGURATION
# =============================================================================

# User configuration
# export MANPATH="/usr/local/man:$MANPATH"
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

# PYTHON PATH
# =============================================================================

# brew installation of python
export PATH=/usr/local/share/python:$PATH

# VIRTUAL ENVS
# =============================================================================

# virtualenvwrapper
VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel
source /usr/local/bin/virtualenvwrapper.sh

# Restrict PIP to virtual environments
export PIP_REQUIRE_VIRTUALENV=true

# Define Global PIP to install packages to root
gpip(){
        PIP_REQUIRE_VIRTUALENV="" PIP "$@"
}
gpip2(){
        PIP_REQUIRE_VIRTUALENV="" PIP2 "$@"
}
gpip3(){
        PIP_REQUIRE_VIRTUALENV="" PIP3 "$@"
}

# PSQL
# =============================================================================

# psql
export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.4/bin

# EDITOR
# =============================================================================

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='subl'
else
  export EDITOR='subl'
fi

# ALIASES
# =============================================================================

# sublime
alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'

# zsh
alias zconfig="subl ~/.zshrc"
alias zource="source ~/.zshrc"

# ssh
alias leukweb1="ssh medinaj@plvleukweb1.mskcc.org"
alias leukgen="ssh medinaj@leukgen.mskcc.org"
alias luna="ssh medinaj@luna.mskcc.org"
alias charon="ssh medinaj@charon.mskcc.org"

# virtualenvs
alias v='workon'
alias v.d='deactivate'
alias v.ls='lsvirtualenv'
alias v.mk='mkvirtualenv'
alias v.rm='rmvirtualenv'
alias v.cd='cdvirtualenv'
alias v.lssitepackages='lssitepackages'

# django
alias dj="python manage.py"
alias dj.test="python manage.py test"

# ZSH CUSTOM CONFIGURATION
# =============================================================================

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias ohmyzsh="mate ~/.oh-my-zsh"
