#!/bin/bash

# ZSH CONFIGURATION
# For more, see: ZSH CUSTOM CONFIGURATION

# Path to your oh-my-zsh installation.
export ZSH=/Users/medinaj/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="robbyrussell"

# Which plugins would you like to load?
# (plugins can be found in ~/.oh-my-zsh/plugins/*)
plugins=(git)

# my oh zsh
source $ZSH/oh-my-zsh.sh

# User configuration, /usr/local/sbin includes rabbitmq paths
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin"

# virtualenvwrapper
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel
source /usr/local/bin/virtualenvwrapper.sh

# Restrict PIP to virtual environments
export PIP_REQUIRE_VIRTUALENV="false"

# psql
export PATH=/Applications/Postgres.app/Contents/Versions/10/bin:$PATH

# See: https://gist.github.com/DanHerbert/9520689
export PATH=$HOME/.npm/bin:$PATH

# my executables
export PATH=/Users/medinaj/Projects/config/bin:$PATH

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR="code"
else
  export EDITOR="code"
fi

# make sure aliases are updated after running _alie
alie () { _alie "$@"; source ~/.alie }

# load registered aliases on new shells
source ~/.alie

# source isabl autocompletion
. /Users/medinaj/Projects/msk/isabl/env/juno/.completion/isabl_zsh.sh

# Make sure I don't need to write ssh password all the time.
ssh-add -K

# added by travis gem
[ -f /Users/medinaj/.travis/travis.sh ] && source /Users/medinaj/.travis/travis.sh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/medinaj/Projects/msk/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/medinaj/Projects/msk/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/medinaj/Projects/msk/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/medinaj/Projects/msk/google-cloud-sdk/completion.zsh.inc'; fi
