#!/bin/bash

# ZSH CONFIGURATION
# For more, see: ZSH CUSTOM CONFIGURATION

# Path to your oh-my-zsh installation.
export ZSH=/Users/medinaj/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="robbyrussell"

# Which plugins would you like to load?
# (plugins can be found in ~/.oh-my-zsh/plugins/*)
plugins=(git)

# my oh zsh
source $ZSH/oh-my-zsh.sh

# User configuration, /usr/local/sbin includes rabbitmq paths
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin"

# virtualenvwrapper
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel
source /usr/local/bin/virtualenvwrapper.sh

# Restrict PIP to virtual environments
export PIP_REQUIRE_VIRTUALENV=true

# Define Global PIP to install packages to root
gpip(){
        PIP_REQUIRE_VIRTUALENV="false" PIP "$@"
}
gpip2(){
        PIP_REQUIRE_VIRTUALENV="false" PIP2 "$@"
}
gpip3(){
        PIP_REQUIRE_VIRTUALENV="false" PIP3 "$@"
}

# psql
export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.4/bin

# See: https://gist.github.com/DanHerbert/9520689
export PATH=$HOME/.npm/bin:$PATH

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR="subl"
else
  export EDITOR="subl"
fi

# sublime
alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'

# zsh
alias zconfig="subl ~/.zshrc"
alias zource="source ~/.zshrc"

# ssh
alias europa="ssh -N -L localhost:8888:localhost:8887 selene"
alias charon="ssh charon"
alias leukgen="ssh leukgen"
alias leukweb1="ssh plvleukweb1"
alias luna="ssh luna"
alias selene="ssh selene"
alias leukbot="ssh -t selene 'chmod 777 /dev/pts/* > /dev/null 2>&1; \
    sudo -i -u leukbot'"

# virtualenvs
alias leukapp='cd ~/Projects/msk/leukapp/master && workon leukapp'

# django
alias dj="python manage.py"

# mount leukgen
alias leukdc="sudo sshfs \
    -o allow_other,defer_permissions,follow_symlinks \
    -o IdentityFile=/Users/medinaj/.ssh/id_rsa \
    medinaj@luna.mskcc.org:/ifs/res/leukgen/local/opt/leukdc /mnt/leukdc"

alias repos="sudo sshfs -o allow_other,defer_permissions \
    medinaj@luna.mskcc.org:/ifs/work/leukgen/home/s/repos \
    /mnt/repos -o IdentityFile=/Users/medinaj/.ssh/id_rsa"

alias master="sudo sshfs \
    -o allow_other,defer_permissions \
    -o IdentityFile=/Users/medinaj/.ssh/id_rsa \
    medinaj@luna.mskcc.org:/ifs/work/leukgen/local/opt /mnt/master"
